# see https://github.com/Ericsson/ecaudit/blob/ecaudit_c3.11-2.11.0/doc/slf4j_logger.md

logger_backend:
    - class_name: com.ericsson.bss.cassandra.ecaudit.logger.Slf4jAuditLogger
      parameters:
      - log_format: "cassandra-tmestamp=${TIMESTAMP} client=${CLIENT_IP}, user=${USER}, status=${STATUS}, operation='${OPERATION}'"