org.opennms.newts.config.datacenter=opennms-lab


# The shortest collection interval configured for any collectable or pollable service, in milliseconds (in this case, 30 seconds).
# Note NO SPACES at end of number
org.opennms.newts.query.minimum_step=30000

# The communication interval for the Newts service, in milliseconds. Should be set to 1.5 times the minimum_step value.
# Note NO SPACES at end of number
org.opennms.newts.query.heartbeat=45000



