reports=xmlfile1.systemcpu, \
 xmlfile1.timecaptured, \
 xmlfile1.periodictime

report.xmlfile1.systemcpu.name=systemCpuUsage
report.xmlfile1.systemcpu.columns=systemCpuUsage
report.xmlfile1.systemcpu.type=nodeSnmp
report.xmlfile1.systemcpu.command=--title="systemCpuUsage" \
 --units-exponent=0 \
 --vertical-label="cpu" \
 DEF:val1={rrd1}:systemCpuUsages:AVERAGE \
 AREA:val1#babdb6 \
 LINE2:val1#888a85:"Online " \
 GPRINT:val1:AVERAGE:"Avg \\: %10.2lf" \
 GPRINT:val1:MIN:"Min \\: %10.2lf" \
 GPRINT:val1:MAX:"Max \\: %10.2lf\\n"

report.xmlfile1.timecaptured.name=timeCaptured
report.xmlfile1.timecaptured.columns=timeCaptured
report.xmlfile1.timecaptured.type=nodeSnmp
report.xmlfile1.timecaptured.command=--title="timeCaptured" \
 --units-exponent=0 \
 --vertical-label="captured" \
 DEF:val1={rrd1}:timeCaptured:AVERAGE \
 AREA:val1#babdb6 \
 LINE2:val1#888a85:"Online " \
 GPRINT:val1:AVERAGE:"Avg \\: %10.2lf" \
 GPRINT:val1:MIN:"Min \\: %10.2lf" \
 GPRINT:val1:MAX:"Max \\: %10.2lf\\n"

report.xmlfile1.periodictime.name=periodocTime
report.xmlfile1.periodictime.columns=periodocTime
report.xmlfile1.periodictime.type=nodeSnmp
report.xmlfile1.periodictime.command=--title="periodicTime" \
 --units-exponent=0 \
 --vertical-label="captured" \
 DEF:val1={rrd1}:periodocTime:AVERAGE \
 AREA:val1#babdb6 \
 LINE2:val1#888a85:"Online " \
 GPRINT:val1:AVERAGE:"Avg \\: %10.2lf" \
 GPRINT:val1:MIN:"Min \\: %10.2lf" \
 GPRINT:val1:MAX:"Max \\: %10.2lf\\n"